[project]
name = "diffmpc-cbf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "casadi>=3.8.0",
    "matplotlib>=3.11.2",
    "numpy>2",
    "qpth",
    "torch",
]

[project.scripts]
diffmpc-cbf = "diffmpc_cbf:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = { path = "../pytorch-whl/torch-2.11.0+cu128-cp311-cp311-manylinux_2_28_x86_64.whl" }
qpth = { workspace = true, editable = true }

[tool.uv.workspace]
members = [
    "thirdparty/qpth",
]
